name = "LZOTools"
uuid = "32aa4ff1-cc5a-4ead-abec-09bb076ef871"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
