name = "LZOTools"
uuid = "32aa4ff1-cc5a-4ead-abec-09bb076ef871"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LZO_jll = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"


[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
